from __future__ import annotations

from types import TracebackType
from typing import Protocol, Sequence
from uuid import UUID

from app.application.history import HistoryEvent
from app.domain import Project, Task, TaskAggregate, WorkType


class TaskRepository(Protocol):
    def add(self, task: Task) -> Task: ...
    def add_aggregate(self, aggregate: TaskAggregate) -> TaskAggregate: ...
    def get(self, task_id: UUID) -> Task | None: ...
    def get_aggregate(self, task_id: UUID) -> TaskAggregate | None: ...
    def list_inbox(self) -> Sequence[Task]: ...


class HistoryRepository(Protocol):
    def append(self, event: HistoryEvent) -> None: ...
    def append_many(self, events: Sequence[HistoryEvent]) -> None: ...


class ProjectRepository(Protocol):
    def add(self, project: Project) -> Project: ...
    def get(self, project_id: UUID) -> Project | None: ...


class WorkTypeRepository(Protocol):
    def add(self, work_type: WorkType) -> WorkType: ...
    def get(self, work_type_id: UUID) -> WorkType | None: ...


class UnitOfWork(Protocol):
    tasks: TaskRepository
    history: HistoryRepository
    projects: ProjectRepository
    work_types: WorkTypeRepository

    def __enter__(self) -> UnitOfWork: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
